version: 2.1
orbs:
  python: circleci/python@2.0.3
  heroku: circleci/heroku@1.2.6

jobs:
  build_and_test: # this can be any name you choose
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Print python version
          command: python -V

      - run:
          name: Download python dependencies
          command: pip3 install -t dep -r requirements.txt

      - run:
          name: package the artifacts
          command: cd dep; zip ../lambda_artifact.zip -rv .

      - run:
          name: list directory
          command: ls -ltr

      - run:
          name: package main program
          command: zip lambda_artifact.zip -u main.py

      - run:
          name: list directory
          command: ls -ltr

      - run:
          name: present workdirectory
          command: pwd

      - store_artifacts:
          path: /home/circleci/project/lambda_artifact.zip

workflows:
  test_my_app:
    jobs:
      - build_and_test
